server:
  port: 8082


mybatis:
  configuration:
    jdbc-type-for-null: 'NULL'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=JST
    username: user01
    password: user01
    driverClassName=com:
      mysql:
        cj:
          jdbc:
            Driver:
